
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Jcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCE = 19;
  public static final int STRING_LITERAL = 15;
  public static final int PAGINA = 30;
  public static final int PARAMETROS = 20;
  public static final int MODIPAG = 24;
  public static final int FECHAMODI = 38;
  public static final int LETRAS = 17;
  public static final int IGUAL = 11;
  public static final int CORDER = 6;
  public static final int TITULO = 33;
  public static final int USUARIOMODI = 39;
  public static final int PADRE = 35;
  public static final int ID = 32;
  public static final int BORRARPAG = 42;
  public static final int IDS = 16;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int AGREGARCOM = 29;
  public static final int CLASE = 31;
  public static final int error = 1;
  public static final int COMILLA = 14;
  public static final int FECHACREA = 37;
  public static final int ATRIBUTOS = 26;
  public static final int ATRIBUTO = 25;
  public static final int ACCION = 8;
  public static final int NUEVOSITIO = 22;
  public static final int CORAB = 18;
  public static final int USUARIOCREA = 36;
  public static final int NOMBREAC = 10;
  public static final int FINAL = 13;
  public static final int PTCOMA = 2;
  public static final int NUEVAPAG = 23;
  public static final int PARAMETRO = 21;
  public static final int ACCIONES = 9;
  public static final int SITIO = 34;
  public static final int INICIO = 7;
  public static final int ETIQUETA = 28;
  public static final int PARDER = 4;
  public static final int CORIZQ = 5;
  public static final int CIERRE = 12;
  public static final int BORRARSITIO = 41;
  public static final int ETIQUETASX = 27;
  public static final int MODICOM = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "INICIO",
  "ACCION",
  "ACCIONES",
  "NOMBREAC",
  "IGUAL",
  "CIERRE",
  "FINAL",
  "COMILLA",
  "STRING_LITERAL",
  "IDS",
  "LETRAS",
  "CORAB",
  "CORCE",
  "PARAMETROS",
  "PARAMETRO",
  "NUEVOSITIO",
  "NUEVAPAG",
  "MODIPAG",
  "ATRIBUTO",
  "ATRIBUTOS",
  "ETIQUETASX",
  "ETIQUETA",
  "AGREGARCOM",
  "PAGINA",
  "CLASE",
  "ID",
  "TITULO",
  "SITIO",
  "PADRE",
  "USUARIOCREA",
  "FECHACREA",
  "FECHAMODI",
  "USUARIOMODI",
  "MODICOM",
  "BORRARSITIO",
  "BORRARPAG"
  };
}

