package Ejecucion;

public enum Accion {
    NUEVO_SITIO_WEB,
    BORRAR_SITIO_WEB,
    NUEVA_PAGINA,
    MODIFICAR_COMPONENTE,
    MODIFICAR_PAGINA,
    BORRAR_PAGINA,
    AGREGAR_COMPONENTE,
    MODIIFICAR_COMPONENTE,
    BORRAR_COMPONENTE

}
